# -*- coding: utf-8 -*-
"""shooping_pattern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17oBDfOc6_Z4DZBGVB4VC928wf5QpQLvj
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("/content/shopping_behavior_updated.csv")

df.info()

df.head(5)

df = df.rename(columns={
    'Item Purchased': 'Item',
    'Purchase Amount (USD)': 'Price',
    'Review Rating': 'Rating',
    'Subscription Status': 'Subscription',
    'Payment Method': 'Payment',
    'Frequency of Purchases': 'Frequency',
    'Discount Applied': 'Discount',
    'Promo Code Used': 'Promo'
})

df['Color'] = df['Color'].str.strip().str.title()

df['Category'] = df['Category'].str.strip().str.title()

df['Item'] = df['Item'].str.strip().str.title()

df['Location'] = df['Location'].str.strip().str.title()

df['Location'] = df['Location'].str.strip().str.title()

df['Season'] = df['Season'].str.strip().str.title()

df['Frequency'] = df['Frequency'].str.strip().str.title()

total_price = df['Price'].sum()
total_price

color_df = df.groupby('Color')['Price'].sum()

color_df = df.groupby('Color')['Price'].sum()

location_spend = df.groupby('Location')['Price'].sum()

gender_df = df.groupby('Gender')['Price'].sum()

lifetime_purchase = df.groupby('Frequency')['Price'].sum()
print("\nLifetime Purchases is:", lifetime_purchase)

previous_sales_category = df.groupby('Category')['Previous Purchases'].count()

gender_total = df.groupby('Gender')['Previous Purchases'].count()

avg_order = df['Price'].mean()
print("\nAverage Orders", round(avg_order, 2))

total_customer = df['Customer ID'].nunique()
print("Total Customers:", total_customer)

most_popular_payment = df['Payment'].mode()[0]

category_sales = df.groupby('Category')['Price'].sum()
item_sales = df.groupby('Item')['Price'].sum().sort_values(ascending=False).head(10)
season_sales = df.groupby('Season')['Price'].sum()
size_sales = df.groupby('Size')['Price'].sum()
color_sales = df.groupby('Color')['Price'].sum()

# Spending by frequency
frequency_sales = df.groupby('Frequency')['Price'].sum()

# Subscription vs non-subscription
subscription_sales = df.groupby('Subscription')['Price'].sum()

# Average rating per category
rating_by_category = df.groupby('Category')['Rating'].mean()

# Previous purchases effect
repeat_customers = df.groupby('Previous Purchases')['Price'].mean()

discount_effect = df.groupby('Discount')['Price'].mean()
promo_effect = df.groupby('Promo')['Price'].mean()

# Cross-check: total revenue with/without discounts
discount_total = df.groupby('Discount')['Price'].sum()
promo_total = df.groupby('Promo')['Price'].sum()

customer_summary = df.groupby('Customer ID').agg({
    'Price':'sum',
    'Previous Purchases':'sum',
    'Frequency':'first',
    'Subscription':'first'
}).reset_index()

# Create spend-based segments
customer_summary['Segment'] = pd.qcut(customer_summary['Price'], q=3, labels=['Low Value','Mid Value','High Value'])

fig, axes = plt.subplots(2, 3, figsize=(16,10))

gender_total.plot(kind='bar', ax=axes[0,0], color='steelblue', title='Customers by Gender', width=0.3)
previous_sales_category.plot(kind='bar', ax=axes[0,1], color='seagreen', title='Prev Sales by Category')
category_sales.plot(kind='pie', ax=axes[0,2], autopct='%1.1f%%', ylabel="", title='Category Sales %')
item_sales.plot(kind='barh', ax=axes[1,0], color='royalblue', title='Top 10 Items')
season_sales.plot(kind='bar', ax=axes[1,1], color='grey', title='Sales by Season')
size_sales.plot(kind='bar', ax=axes[1,2], color='orange', title='Sales by Size')
plt.xticks(rotation=0)

plt.tight_layout()
plt.show()

